# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: MyHostedVM

steps:
- task: Maven@3
  displayName: Maven Build
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'pre-integration-test'
    options: '-P PostgreSQL'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false

- task: Docker@2
  displayName: Docker Image Build
  inputs:
    containerRegistry: 'infykubedemoregistry'
    repository: $(repository)
    tags: $(tag)
    command: 'build'
    Dockerfile: 'Dockerfile'
  
- task: CmdLine@2
  displayName: Trivy Scanning
  inputs:
    script: 
      
      trivy image --exit-code 0 --severity LOW,MEDIUM $(registryName)/$(repository):$(tag)
      
      echo 'checking for HIGH , CRITICAL'

      trivy image --exit-code 0 --severity HIGH,CRITICAL $(registryName)/$(repository):$(tag)
- task: Docker@2
  enabled: true
  displayName: Docker push
  inputs:
    containerRegistry: 'infykubedemoregistry'
    repository: '$(repository)'
    tags: $(tag)
    command: 'push'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'helm-chart'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'helmcharts'
    publishLocation: 'Container'    

     

